### ISSUE TITLE
Saving after Mac shut down

### ISSUE THREAD

**Issue by emmanuel1212** [fuermosi777/meny-feedback#1]
Hello

I love Meny BUT when I shut down my Mac I either forget to save my notes or sometimes cannot do it (e.g. because there was a crash). Would it be possible to have Meny automatically save the memo so no data is lost?

Thanks

**Comment by fuermosi777** [comment]
I will look into this.

**Comment by fuermosi777** [comment]
If you save the file to somewhere on the disk, it will be automatically saved while you are editing. 

To save a file, click bottom left corner icon, and choose "Save As". Select a location then click "Save". After that, whatever is typed in the editor will be saved in the file automatically.

Let me know if you have any other questions. Thank you.
